version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: docker/Dockerfile
    container_name: app
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      - mysql
    ports:
      - '3000:3000' # ここを追加（Vite の開発サーバー用）
    networks:
      - talk-to-world-network

  api:
    build:
      context: ./api
      dockerfile: docker.dev/Dockerfile
    container_name: api
    volumes:
      - ./api/cmd:/app
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - talk-to-world-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - talk-to-world-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8090:80'
    volumes:
      - ./app/src:/var/www/html
      - ./app/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - talk-to-world-network

networks:
  talk-to-world-network:
    driver: bridge

volumes:
  db_data:
